name: Blanq test ubuntu-latest g++ unexpected

on:
  push:
    paths:
    - 'include/**'
    - 'src/**'
    - '.github/workflows/test-ubuntul-unexpected-gcc.yml'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        BUILD_TYPE: [Debug, Release]
        target: [test-instantiate-using-lambda-explicit]
        compiler: [g++-13]
        include:
          - os: ubuntu-latest
            compiler: g++-13
            install: sudo apt update && sudo apt install g++-13
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install compiler
      shell: bash
      run: ${{ matrix.install }}

    - name: Create Build Environment
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake .. -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: if cmake --build . --config ${{matrix.BUILD_TYPE}} -t ${{matrix.target}} -j; then exit 1; fi

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: if ./${{matrix.target}}; then exit 1; fi
