name: Blanq test ubuntu-latest

on:
  push:
    paths:
    - 'include/**'
    - 'src/**'
    - '.github/workflows/test_ubuntul.yml'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        BUILD_TYPE: [Debug, Release]
        target: [test-constrained-fold-explicit, test-constrained-fold-implicit]
        compiler: [g++-10, g++-13, clang++-14, clang++-15]
        include:
          - os: ubuntu-latest
            compiler: g++-10
            install: sudo apt update && sudo apt install g++-10
          - os: ubuntu-latest
            compiler: g++-13
            install: sudo apt update && sudo apt install g++-13
          - os: ubuntu-latest
            compiler: clang++-14
            install: sudo apt update && sudo apt install clang-14
          - os: ubuntu-latest
            compiler: clang++-15
            install: sudo apt update && sudo apt install clang-15
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install compiler
      shell: bash
      run: ${{ matrix.install }}

    - name: Create Build Environment
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake .. -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{matrix.BUILD_TYPE}} -t ${{matrix.target}} -j

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ./${{matrix.target}}
